### ISSUE TITLE
can you provide an example?

### ISSUE THREAD

**Issue by varna9000** [popnotsoda95/async_urequests#1]
How do you implement the response in other async code?

when I do:
` res=requests.get("http://xxx.xxx.xxx.xxx")
print(res.content)
`
I get
`AttributeError: 'generator' object has no attribute 'content'`

Should I yeild the result somehow?

**Comment by StevenRuest** [comment]
you need to use "await", so:
res = await requests.get("http://xxx.xxx.xxx.xxx")
